---
extends: "@spalger/personal/es6"
env:
  jest: true
  node: true
rules:
  no-constant-condition:
    - error
    - checkLoops: false
  import/no-internal-modules:
    - error
    - allow:
      - rxjs/Rx
      - express-brute/lib/AbstractClientStore